### ISSUE TITLE
Add new table for AQ40 relics/scarabs

### ISSUE THREAD

**Issue by vely-digital** [ps-wow/Adibags_ByExpansion#8]
Hey, I'm using this addon for a while now. 
I do AQ every week for transmog etc. Relics and scarabs are awkward when they all go to Quest and are not filtered, can I open pull request and put them inside new AdiBags_ByExpansion_WoW/raids/AQ40-Relics. 
I was thinking about new module part because if we put them in normal AQ40 module, it will be bloated and confusing if relics and items merge together.

P.S. great job with this addon mate 👍

**Comment by davidcraig** [comment]
Hi, thanks for the comment, I've also recently been running AQ on my warlock and found the same thing, I did make my own manual filter for it, as you say it doesn't really fit into any of the other categories right now.

I am more than happy to accept PR's :) I think more addons should embrace open source and community contribution, that's why all my addons are on GitHub, it makes it much easier to share idea's and get valuable insights from the community such as this :)

**Comment by davidcraig** [comment]
Merged and Build scripts ran, closing issue :)
